project/project/Scripts/dj_project/dj_app/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',v.home),
    path('adduser',v.add_user),
    path('login',v.login_view),
    path('logout',v.logout_view),

    path('product',v.product_view),
    path('addtocart/<int:pid>',v.add_to_cart,name='addtocart'),
    path('clist',v.cart_list),

    path('remove/<int:pro>',v.remove_view),

    path('search_product',v.Search),
    #path('ixt/<str:ixt2>/',v.sortby_type,name='list2'),

    path('product/<str:category_name>/',v.category_page,name='category_page'),
    path('sidebar',v.sidebar),
    path('filter/<int:pid>',v.filter_cate),
    path('update_cart/<int:item_id>/<str:action>/',v.update_cart,name='update_cart'),
    path('success',v.success_view),
]

project/project/Scripts/dj_project/dj_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('dj_app.urls','dj_app'),namespace='dj_app')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

project/project/Scripts/dj_project/dj_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    c_name=models.CharField(max_length=30)
    
    class Meta:
        db_table:'category'

    def __str__(self):
        return self.c_name

class Product(models.Model):
    img=models.ImageField(upload_to='image',default='')
    p_name=models.CharField(max_length=50)
    p_price=models.IntegerField()
    p_description=models.TextField(max_length=200)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)

    class Meta:
        db_table:'product'

class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    class Meta:
        db_table='cart'





    

    

project/project/Scripts/dj_project/dj_app/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login,logout
from .models import Product,Cart,Category
from django.views.generic import DeleteView
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
import razorpay

from django.contrib.auth.hashers import make_password 
# Create your views here.
def home(request):
    return render(request,'home.html')


def add_user(request):
    if request.method=='POST':
        #f=UserCreationForm(request.POST)
        uname=request.POST.get('username')
        passw=request.POST.get('password')
        c_pass=request.POST.get('cpassword')
        u=User()
        u.username=uname
        u.password=passw

        user=User.objects.filter(username=uname)
        if len(uname) >10:
            messages.error(request,"Username must be under 10 characters")
            return redirect('/adduser')
        if passw != c_pass:
            messages.error(request,"Passwords do not match")
            return redirect('/adduser')
        if user.exists():
            messages.info(request, "Username is already taken")
            return redirect('/adduser')

        u = User(username=uname)
        u.set_password(passw)  # This hashes the password correctly
        u.save()
        #u.save()
        return redirect('/')
    else:
        f=UserCreationForm
        context={'form':f}
        return render(request,'adduser.html',context)


def login_view(request):
    if request.method=='POST':
        uname=request.POST.get('username')
        passw=request.POST.get('password')
        user=authenticate(request,username=uname,password=passw)
        user1=User.objects.filter(username=uname)
        if user1.exists():
            if user is not None:
                if user.is_active:
                    request.session['uid']=user.id
                    login(request,user)
                    return redirect('/')
                else:
                    messages.error(request, "Your account is inactive.")
                    return redirect('/login')
            else:
                return render(request,'login.html')
                
        else:
            messages.info(request, "You are not register")
            return redirect('/login') 
    else:
        return render(request,'login.html')

def logout_view(request):
    logout(request)
    return redirect('/')


def product_view(request):
    #pl=Product.objects.all()
    #context={'pl':pl}
    #return render(request,'product.html',context)

    #pl=Product.objects.filter()
    #inc=set()
    #for i in pl:
        #inc.add(i.category.c_name)
    #context={'pl':pl,'inc':inc}
    #return render(request,'product.html',context)

    
    cate=Category.objects.all()
    pl=Product.objects.all()
    context={'Cate':cate,'pl':pl}
    return render(request,'product.html',context)


def add_to_cart(request,pid):
    product_id=Product.objects.get(id=pid)
    uid=request.session.get('uid')
    user_id=User.objects.get(id=uid)
    if Cart.objects.filter(user_id=uid,product=product_id).exists():
        return redirect('/product')
    c=Cart()


    c.product=product_id
    c.user=user_id
    c.save()
    return redirect('/product')

def cart_list(request):
    uid=request.session.get('uid')
    user_id=User.objects.get(id=uid)
    cl=Cart.objects.filter(user_id=uid)

    total_price= sum((item.product.p_price)*item.quantity for item in cl)
    final_price=total_price * 100

    if final_price < 100 :
        return render(request,'cart.html', {
            'cl':cl,
            'error':'order amount is too low.Please add more items to your cart.'
        })

    client=razorpay.Client(auth=(settings.RAZORPAY_KEY_ID,settings.RAZORPAY_KEY_SECRET))
    payment=client.order.create({'amount':final_price,'currency':'INR','payment_capture':'1'})
    print(payment)

    request.session['razorpay_order_id']=payment['id']
    context={'cl':cl,'total_price':total_price,
        'final_price':final_price,'razorpay_key_id':settings.RAZORPAY_KEY_ID,
        'razorpay_order_id':payment['id']}

    return render(request,'cart.html',context)


def remove_view(request,pro):
    remo=Cart.objects.get(id=pro)
    remo.delete()
    return redirect('/clist')


def Search(request):

    uid=request.session.get('uid')
    srch=request.POST.get('srch')
    pl=Product.objects.filter(p_name__contains=srch)
    context={'pl':pl}
    return render(request,'product.html',context)



def category_page(request,category_name):
    #fname=request.session.get('fname',None)
    cate=Category.objects.all()
    pl=Product.objects.all()
    filtered_product=Product.objects.filter(category_name=category_name)
    context={'Cate':cate,'f_product':filtered_product,'pl':pl}
    return render(request,'product.html',context)

def filter_cate(request,pid):
    #uid=request.session.get('uid')
    #user=User.objects.get(id=uid)
    # cateid=Category.objects.get(id=pid)
    
    product=Product.objects.filter(category_id=pid)
    cate=Category.objects.all()
    pl=Product.objects.all()
    context={'Cate':cate,'product':product,'pl':pl}
    return render(request,'cat.html',context)

def sidebar(request):
    cate=Category.objects.all()
    context={'Cate':cate}
    return render(request,'category_list.html',context)


def update_cart(request,item_id,action):
    cart_item=get_object_or_404(Cart,id=item_id,user=request.user)

    if action=='increase':
        cart_item.quantity += 1
    elif action=='decrease':
        cart_item.quantity -= 1
        if cart_item.quantity < 1:
            cart_item.delete()
            return redirect('/clist')

    cart_item.save()
    return redirect('/clist')
    
@csrf_exempt
def success_view(request):
    if request.method=='POST':
        a=request.POST
        print(a)
        return render(request,'success.html')
    else:
        return render(request,'success.html')

project/project/Scripts/dj_project/dj_app/templates/adduser.html
{%include 'navbar.html'%}
{%load static%}
<link rel="stylesheet" href="{%static 'css/bmin.css'%}">
<style>
    body{
        background-color: white;
    }
    .square{
        height: 500px;
        width: 600px;
        background-color: white;
        margin-top: 60px;
        margin-left: 450px;
        box-shadow: 0px 0px 10px black;
    }
    h2{
        text-align: center;
    }
    #btnsubmit{
        background-color: rgb(21, 25, 41);
        color: white;
        width: 80px;
        height: 35px;
        border: none;
    }
    .login-form {
        display: flex;
        flex-direction: column;
    }
    .form-row {
        margin-bottom: 20px;
        margin-left: 170px;
        margin-top: 10px;
    }
    .form-actions {
        display: flex;
        gap: 10px; 
        margin-left: 250px;
    }
    .msgs{
        margin-left: 200px;
    }
    #cpass{
        margin-left:110px;
    }
    .alert-primary{
        width: 262px;
        height: 40px;
        border-radius: 5px;
        text-align: center;
        background-color: #cfe2ff;
        margin-left: 170px;
        padding-top:10px;
    }

</style>

<div class="square">
    <h2>Registration</h2>
    <form action="" method="post">
        {%csrf_token%}
        {% if messages %}
        {{ message.tags }}
        <div class="alert-primary" role="alert">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </div>
        {% endif %}
        <div class="login-form">
            
            
            <div class="form-row">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-row">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <!--<div class="form-row">-->
                <div id="cpass">
                <label for="password">Confirm Password:</label>
                <input type="password" id="cpassword" name="cpassword" required>
                </div><br><br>
            <!--</div>-->
            <div class="form-actions">
                <input type="submit" value="save" id="btnsubmit">
                
            </div><br>
            <div class="msgs"><p>Already have account<a href="adduser">sign up</a></p></div>
        </div>
    </form>
    </div>



<!--<div class="square">
    <form action="" method="post">
    
        {%csrf_token%}
        <table class="table">
            <h2>Registration</h2>
            {{form.as_table}}
            <div class="form-actions">
            <tr>
                <td><input type="submit" value="save" id="btnsubmit"></td>
                <td><input type="reset" value="reset" id="btnreset"></td>
                <p>Already have account<a href="login">login</a></p>
            </tr>
        </div>
        </table>
    
    </form>
</div>-->

project/project/Scripts/dj_project/dj_app/templates/cart.html
{%include 'navbar.html'%}
{%load static%}
<link rel="stylesheet" href="{%static 'css/bmin.css'%}">

<style>
    body{
        background-color: white;
    }
    .calci{
        background-color: #E2E7E6;
        width: 350px;
        height: 200px;
        margin-left: 600px;
        margin-top: 100px;
        padding-left: 40px;
        padding-top: 30px;
        box-shadow:0px 0px 10px black ;
        position: fixed;
        top: 30px;
        right: 20px;
        box-sizing: border-box;
    }
    .cart{
        width: 70%;
    }
    .plcbtn{
        margin-left: 80px;
    }
    #removebtn{
        text-decoration: none;
    }
</style>
<div class="cart">
<table class="table">
    <tr>
        <!--<th>Id</th>-->
        <th>Image</th>
        <th>Product Name</th>
        <th>Product Price</th>
        <th>Product Quantity</th>
        <!--<th>Username</th>-->
        <th>Subtotal</th>
        <th>Action</th>
    </tr>

    {%for i in cl%}
    <tr >
        <!--<td>{{i.product.id}}</td>-->
        <td><img src="{{i.product.img}}" alt="image not uploaded" width="100px" height="100px"></td>
        <td>{{i.product.p_name}}</td>
        <td>{{i.product.p_price}}</td>
        <!--<td><input type="number" name="qty" value="1" min="1" onchange="updateSubtotal(this)"></td>-->
        <td >
            <form method="post" action="{% url 'dj_app:update_cart' i.id 'increase' %}">
                {%csrf_token%}
                <button type="submit" class="btn btn-success btn-sm">+</button>
            </form>
            {{i.quantity}}
            <form method="post" action="{% url 'dj_app:update_cart' i.id 'decrease' %}">
                {%csrf_token%}
                <button type="submit" class="btn btn-danger btn-sm">-</button>
            </form>
        </td>
        <!--<td>{{i.user.username}}</td>-->
        <!--<td><input type="text" class="subtotal" value="{{i.product.p_price}}"></td>-->
        <td><input type="text" class="subtotal" value="{%widthratio i.product.p_price 1 i.quantity%}" readonly></td>
        <td><a href="remove/{{i.id}}" id="removebtn">Remove</a></td>

        
    </tr>
    {%endfor%}

</table>
</div>

<div class="calci">
<h3 id="total">Final Total:Rs.<span id="total-value">0.00/-</span></h3><br>
<!--<button class="plcbtn">Place Order</button>-->
<!--<h3 id="gst">GST (18%):Rs.<span id="gst-value">0.00/-</span></h3>
<h3 id="invoice-total">Final Total:Rs.<span id="invoice-total-value">0.00/-</span></h3>-->
</div>

<script src="{%static 'js/bmin.js'%}"></script>
<script src="{%static 'js/p.js'%}"></script>
<script src="{%static 'js/static.js'%}"></script>


<form action="/success" method="POST">
    {%csrf_token%}
    <script
       src="https://checkout.razorpay.com/v1/checkout.js"
        data-key="rzp_test_s28zPR4YDfC6Kg" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
        data-amount="{{final_price}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
        data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
        data-order_id="{{ razorpay_order_id}}"// Replace with the order_id generated by you in the backend.
        data-buttontext="Pay with Razorpay"
        data-name="Cosmetic shop"
        data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
        data-image="https://example.com/your_logo.jpg"
        data-prefill.name="Gaurav Kumar"
        data-prefill.email="gaurav.kumar@example.com"
        data-theme.color="#F37254"
    ></script>
    <input type="hidden" custom="Hidden Element" name="hidden"/>
    </form>

project/project/Scripts/dj_project/dj_app/templates/cat.html
{%extends 'category_list.html'%}
{%load static%}
{%block body%}
<link rel="stylesheet" href="{%static 'css/bmin.css'%}">

<style>
  body{
    position: static;
  }
</style>

<div class="album py-5 bg-light">
  
    <div class="container">
      
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {%for i in product%}
        <!--<h1 id="all_products_heading">{{i.category.c_name}}</h1>-->
        <div class="col">
          <div class="card shadow-sm">
            
            <div class="card-body" title="{{i.p_name}}">
              
                <img class="product_img" src="{{ i.img.url }}" width="100%" height="270px" alt="{{ i.p_name }}">
                <p class="card-text">{{i.p_name}}</p>
              <p class="card-text">{{i.p_price}}</p>
              <p class="card-text">{{i.p_description}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary" ><a href="addtocart/{{i.id}}">Addtocart</a></button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <!--<small class="text-muted">9 mins</small>-->
              </div>
            </div>
          </div>
        </div>
        
        {%endfor%}
        
        </div>
      
    </div>
  </div>
<script src="{%static 'js/bmin.js'%}"></script>
<script src="{%static 'js/p.js'%}"></script>
{%endblock%}

project/project/Scripts/dj_project/dj_app/templates/category_list.html
{%include 'navbar.html'%}
{%load static%}

<link rel="stylesheet" href="{%static 'css/bmin.css'%}">
<style>
    *{
        list-style: none;
        text-decoration: none;
    }
    .grid1{
        background-color: white;
        position: fixed;
        left: 0;
        width: 200px;
        height: 100%;
    }
    .all_cate{
        color: black;
    }
    .cate_list a{
        display: block;
        height: 100%;
        width: 100%;
        line-height: 65px;
        font-size: 20px;
        padding-left: 40px;
        box-sizing: border-box;
        text-decoration: none;
    }
    .all_catelist{
        color: black;
    }
    .main{
        padding-left: 210px;
    }
</style>
    
        <div class="grid1">
            <div class="cate_list">
                <a href="/product">
                    <div class="all_catelist">
                        
                        <p>All Products</p>
                    </div>
                </a>
                
                {%for i in Cate%}
                <a href="/filter/{{i.id}}">
                    <div class="all_cate">
                        
                        <p>{{ i.c_name }}</p>
                    </div>
                </a>
                {%endfor%}
            </div>
        </div>
        <div class="main">
            {%block body%}
    
            {%endblock%}
        </div>
        

        <script src="{%static 'js/bmin.js'%}"></script>
        <script src="{%static 'js/p.js'%}"></script>

project/project/Scripts/dj_project/dj_app/templates/home.html
{%load static%}
{%include 'navbar.html'%}
<link rel="stylesheet" href="{%static 'css/bmin.css'%}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <style>
        .home{
            min-height: 100vh;
            display: flex;
            align-items: center;
            opacity: 1;
            background: url('static/images/homepic.avif')no-repeat;
            background-size: cover;
            background-position: center;
        }
        .bty{
            height: 200px;
            width: 200px;
            color: black;
            /*background-color: aqua;*/
            margin-left: 200px;
            font-size: 60px;
        }
    </style>
</head>
<body>
    <section class="home">
       <div class="bty">
        Try our Beauty Products
       </div>
    </section>
    
</body>
</html>

project/project/Scripts/dj_project/dj_app/templates/login.html
{%include 'navbar.html'%}
{%load static%}
<link rel="stylesheet" href="{%static 'css/bmin.css'%}">
<style>
    body{
        background-color: white;
    }
    .sqr{
        height: 500px;
        width: 600px;
        background-color: white;
        /*border: 2px solid black;*/
        margin-top: 70px;
        margin-left: 460px;
        padding-top: 40px;
        box-shadow: 0px 0px 10px black;
    }
    /*.logintb{
        padding-left: 65px;
        padding-top: 50px;
        line-height: 40px;
    }
    .td1{
        padding-left: 60px;
        
    }
    .td2{
        width: 380px;
    }
    #lg1{
        margin-left: 100px;
        width: 70px;
        margin-top: 50px;
    }
    #lg2{
        margin-left: 150px;
        width: 70px;
        margin-top: 50px;   
    }*/
    h2{
        text-align: center;
    }

    .login-form {
        display: flex;
        flex-direction: column;
    }
    .form-row {
        margin-bottom: 20px;
        margin-left: 170px;
        margin-top: 10px;
    }
    .form-actions {
        display: flex;
        gap: 10px; 
        margin-left: 250px;
    }
    #btnlogin{
        background-color: rgb(21, 25, 41);
        color: white;
        width: 80px;
        height: 40px;
        border: none;
    }
    #btnreset{
        background-color: rgb(21, 25, 41);
        color: white;
        width: 80px;
        border: none;
    }
    #signin{
        font-weight: 40px;
    }
    .msg{
        margin-left: 200px;
        margin-top: 20px;
    }
    .alert-primary{
        width: 262px;
        height: 40px;
        border-radius: 5px;
        text-align: center;
        background-color: #cfe2ff;
        margin-left: 170px;
        padding-top:10px;
    }


</style>



<div class="sqr">
    <h2 id="signin">Sign in</h2>
    <form action="" method="post">
        {%csrf_token%}
        {% if messages %}
        {{ message.tags }}
        <div class="alert alert-primary" role="alert">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </div>
        {% endif %}
        <div class="login-form">
            
            
            <div class="form-row">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required> 
            </div>
            <div class="form-row">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <div class="form-actions">
                <input type="submit" value="login" id="btnlogin">
                <input type="reset" value="reset" id="btnreset">
                
            </div>
            <div class="msg"><p>Don't have account<a href="adduser">sign up</a></p></div>
        </div>
    </form>
    </div>
    

project/project/Scripts/dj_project/dj_app/templates/navbar.html
{%load static%}
{%block content%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <style>
        .menubar{
            /*background-color: rgb(21, 25, 41);*/
            background-color: black;
            display: flex;
            height: 55px;
            top: 0;    
            position: sticky;
            z-index: 999;
        }
        .menuul{
            list-style-type: none;
            /*padding: 16px;*/
            padding: 3px;
            margin-top: 0;
            
        }
        .menuul li :hover{ 
            color: blue;           
        }
        .navlist{
            display: inline-block;
            width: 100px;   
            font-size: 18px;
            font-weight: bold;
            padding-top: 10px;
        }
        .srchinput{
            width: 300px;
            
        }
        .anch{
            text-decoration: none;
            color: white;
            margin-left: 30px;
           
            
        }
        #us{
            margin-right: 250px;
            position: absolute;
            padding-left: 180px;
        }
        #lgid{
            margin-left: 35px;
        }
        .fmsrch{
            padding-top: 14px;
            margin-left: 500px;
            display: flex;
        }
        #btn{
            color: white;
            background-color: black;
            border: none;
        }
        #nam{
            color: white;
            font-family: Handjet;
        }
        #cos{
            font-family: Georgia, 'Times New Roman', Times, serif;
        }
        #home{
            font-family: Cedarville Cursive;
            font-size: 30px;
            
        }
        
    </style>
</head>
<body>
    <nav class="menubar">
        <ul class="menuul">
            <!--<li id="cos" class="navlist"><a class="anch">Cosmetics</a></li>-->
            <!--<img src="static/images/beautylogo.png" width="120px" height="50px">-->
            <li class="navlist" ><a href="/" class="anch" id="home"><u><i>Beauty</i></u></a></li>
            <li class="navlist"><a href="/product" class="anch">Product</a></li>
            {%if user.is_authenticated%}
            
            <li class="navlist"><a href="clist" class="anch">Cart</a></li>
            <!--<a class="anch"><i class="fa-solid fa-cart-shopping"></i></a>-->
            <li class="navlist"><a href="logout" class="anch">Logout</a></li>
            <li class="navlist" style="color: blue;" id="us">Welcome:<span id="nam">{{user}}</span></li>
            {%else%}
            <li class="navlist"><a href="adduser" class="anch">Registration</a></li>
            <li class="navlist"><a href="login" class="anch" id="lgid">Login</a></li>
            {%endif%}
        </ul>
        
        <form action="search_product" method="post">
            <div class="fmsrch">
            {%csrf_token%}
            <input type="text" name="srch" placeholder="searchProduct" rows="3" cols="60" class="srchinput">
            <input type="submit" value="search" id="btn">
            </div>
        </form>
    
    </nav>
</body>
</html>
{%endblock content%}

project/project/Scripts/dj_project/dj_app/templates/product.html
{%extends 'category_list.html'%}
{%load static%}
{%block body%}
<link rel="stylesheet" href="{%static 'css/bmin.css'%}">
<style>
  body{
        background-color: #E2E7E6;
    }
 .btn btn-sm btn-outline-secondary{
  background-color: #E2E7E6;
  width: 20px;
 }
 #addtobtn{
  text-decoration: none;
 }
</style>




<div class="album py-5 bg-light">
  
    <div class="container">
     {%if pl%}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {%for i in pl%}
        <div class="col">
          <div class="card shadow-sm">
            <!--<svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>-->


            <div class="card-body" title="{{i.product.category}}">
              
                <img src="{{i.img}}" alt="image not uploaded" width="100%" height="270px">
              <p class="card-text">{{i.p_name}}</p>
              <p class="card-text">{{i.p_price}}</p>
              <p class="card-text">{{i.p_description}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary" ><a href="addtocart/{{i.id}}" id="addtobtn">Addtocart</a></button>
                  
                </div>
                <!--<small class="text-muted">9 mins</small>-->
              </div>
            </div>
          </div>
        </div>
        
        {%endfor%}
        
        </div>
      {%else%}
      <h1>No Result Found</h1>
      {%endif%}
    </div>
  </div>

  
        
        

 

<script src="{%static 'js/bmin.js'%}"></script>
<script src="{%static 'js/p.js'%}"></script>
{%endblock%}

  

project/project/Scripts/dj_project/dj_app/templates/success.html
{%include 'navbar.html'%}
<style>
    .text-center{
        width: 500px;
        height: 300px;
        margin-top: 150px;
        margin-left: 500px;
        box-shadow: 0px 0px 10px  black;
    }
    img{
        margin-left: 150px;
        margin-top: 30px;
    }
    h2{
        margin-left: 40px;
    }
</style>

<div class="text-center">
    <img src="https://www.svgrepo.com/show/157817/success.svg" alt="" class='img-fluid' style="height: 200px;">
    <h2>Thanks Your Payment has been received</h2>

</div>